name: Docker Image CI - X86_64/AARCH64 for Alpine Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # run it manually
  workflow_dispatch:    

jobs:

  build:

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --tag builder .

    - name: build static program with alpine linux docker 
      run: |
        docker run --cidfile=builder.cid builder true
        docker cp "$(cat builder.cid):work/artifact/." .

    - name: Upload static program
      uses: actions/upload-artifact@v4
      with:
        name: unbound-${{ matrix.os }}
        path: ./*.tar.xz
